export const raceData = [
  {
    2024: {
      "01": {
        "01": [
          {
            id: 1,
            name: "اسم السباق 1",
            classification: "التصنيف 1",
            date: "06/01/2024",
            day: "السبت",
            time: "05:30 PM - 03:30 PM",
            distance: "كم 4",
            type: "رملى",
            age: "3 سنوات",
            award: "100.000 ر.س",
          },
          {
            id: 2,
            name: "اسم السباق 2",
            classification: "التصنيف 2",
            date: "06/02/2024",
            day: "الأحد",
            time: "06:30 PM - 04:30 PM",
            distance: "كم 5",
            type: "عشبى",
            age: "4 سنوات",
            award: "105.000 ر.س",
          },
          {
            id: 3,
            name: "اسم السباق 3",
            classification: "التصنيف 3",
            date: "06/03/2024",
            day: "الاثنين",
            time: "07:30 PM - 05:30 PM",
            distance: "كم 6",
            type: "رملى",
            age: "5 سنوات",
            award: "110.000 ر.س",
          },
          {
            id: 4,
            name: "اسم السباق 4",
            classification: "التصنيف 4",
            date: "06/04/2024",
            day: "الثلاثاء",
            time: "08:30 PM - 06:30 PM",
            distance: "كم 7",
            type: "عشبى",
            age: "6 سنوات",
            award: "115.000 ر.س",
          },
          {
            id: 5,
            name: "اسم السباق 5",
            classification: "التصنيف 5",
            date: "06/05/2024",
            day: "الأربعاء",
            time: "09:30 PM - 07:30 PM",
            distance: "كم 8",
            type: "رملى",
            age: "7 سنوات",
            award: "120.000 ر.س",
          },
          {
            id: 6,
            name: "اسم السباق 6",
            classification: "التصنيف 6",
            date: "06/06/2024",
            day: "الخميس",
            time: "10:30 PM - 08:30 PM",
            distance: "كم 9",
            type: "عشبى",
            age: "8 سنوات",
            award: "125.000 ر.س",
          },
          {
            id: 7,
            name: "اسم السباق 7",
            classification: "التصنيف 7",
            date: "06/07/2024",
            day: "الجمعة",
            time: "11:30 PM - 09:30 PM",
            distance: "كم 10",
            type: "رملى",
            age: "9 سنوات",
            award: "130.000 ر.س",
          },
          {
            id: 8,
            name: "اسم السباق 8",
            classification: "التصنيف 8",
            date: "06/08/2024",
            day: "السبت",
            time: "12:30 PM - 10:30 AM",
            distance: "كم 11",
            type: "عشبى",
            age: "10 سنوات",
            award: "135.000 ر.س",
          },
          {
            id: 9,
            name: "اسم السباق 9",
            classification: "التصنيف 9",
            date: "06/09/2024",
            day: "الأحد",
            time: "01:30 PM - 11:30 AM",
            distance: "كم 12",
            type: "رملى",
            age: "11 سنوات",
            award: "140.000 ر.س",
          },
          {
            id: 10,
            name: "اسم السباق 10",
            classification: "التصنيف 10",
            date: "06/10/2024",
            day: "الاثنين",
            time: "02:30 PM - 12:30 PM",
            distance: "كم 13",
            type: "عشبى",
            age: "12 سنوات",
            award: "145.000 ر.س",
          },
        ],
        "02": [],
        "03": [],
        "04": [],
        "05": [],
        "06": [],
      },
    },
  },
  {
    2025: {
      "01": {
        "01": [
          {
            id: 1,
            name: "اسم السباق 1",
            classification: "التصنيف 1",
            date: "06/01/2024",
            day: "السبت",
            time: "05:30 PM - 03:30 PM",
            distance: "كم 4",
            type: "رملى",
            age: "3 سنوات",
            award: "100.000 ر.س",
          },
          {
            id: 2,
            name: "اسم السباق 2",
            classification: "التصنيف 2",
            date: "06/02/2024",
            day: "الأحد",
            time: "06:30 PM - 04:30 PM",
            distance: "كم 5",
            type: "عشبى",
            age: "4 سنوات",
            award: "105.000 ر.س",
          },
          {
            id: 3,
            name: "اسم السباق 3",
            classification: "التصنيف 3",
            date: "06/03/2024",
            day: "الاثنين",
            time: "07:30 PM - 05:30 PM",
            distance: "كم 6",
            type: "رملى",
            age: "5 سنوات",
            award: "110.000 ر.س",
          },
          {
            id: 4,
            name: "اسم السباق 4",
            classification: "التصنيف 4",
            date: "06/04/2024",
            day: "الثلاثاء",
            time: "08:30 PM - 06:30 PM",
            distance: "كم 7",
            type: "عشبى",
            age: "6 سنوات",
            award: "115.000 ر.س",
          },
          {
            id: 5,
            name: "اسم السباق 5",
            classification: "التصنيف 5",
            date: "06/05/2024",
            day: "الأربعاء",
            time: "09:30 PM - 07:30 PM",
            distance: "كم 8",
            type: "رملى",
            age: "7 سنوات",
            award: "120.000 ر.س",
          },
          {
            id: 6,
            name: "اسم السباق 6",
            classification: "التصنيف 6",
            date: "06/06/2024",
            day: "الخميس",
            time: "10:30 PM - 08:30 PM",
            distance: "كم 9",
            type: "عشبى",
            age: "8 سنوات",
            award: "125.000 ر.س",
          },
          {
            id: 7,
            name: "اسم السباق 7",
            classification: "التصنيف 7",
            date: "06/07/2024",
            day: "الجمعة",
            time: "11:30 PM - 09:30 PM",
            distance: "كم 10",
            type: "رملى",
            age: "9 سنوات",
            award: "130.000 ر.س",
          },
          {
            id: 8,
            name: "اسم السباق 8",
            classification: "التصنيف 8",
            date: "06/08/2024",
            day: "السبت",
            time: "12:30 PM - 10:30 AM",
            distance: "كم 11",
            type: "عشبى",
            age: "10 سنوات",
            award: "135.000 ر.س",
          },
          {
            id: 9,
            name: "اسم السباق 9",
            classification: "التصنيف 9",
            date: "06/09/2024",
            day: "الأحد",
            time: "01:30 PM - 11:30 AM",
            distance: "كم 12",
            type: "رملى",
            age: "11 سنوات",
            award: "140.000 ر.س",
          },
          {
            id: 10,
            name: "اسم السباق 10",
            classification: "التصنيف 10",
            date: "06/10/2024",
            day: "الاثنين",
            time: "02:30 PM - 12:30 PM",
            distance: "كم 13",
            type: "عشبى",
            age: "12 سنوات",
            award: "145.000 ر.س",
          },
          {
            id: 11,
            name: "اسم السباق 11",
            classification: "التصنيف 11",
            date: "06/11/2024",
            day: "الثلاثاء",
            time: "03:30 PM - 01:30 PM",
            distance: "كم 14",
            type: "رملى",
            age: "13 سنوات",
            award: "150.000 ر.س",
          },
          {
            id: 12,
            name: "اسم السباق 12",
            classification: "التصنيف 12",
            date: "06/12/2024",
            day: "الأربعاء",
            time: "04:30 PM - 02:30 PM",
            distance: "كم 15",
            type: "عشبى",
            age: "14 سنوات",
            award: "155.000 ر.س",
          },
          {
            id: 13,
            name: "اسم السباق 13",
            classification: "التصنيف 13",
            date: "06/13/2024",
            day: "الخميس",
            time: "05:30 PM - 03:30 PM",
            distance: "كم 16",
            type: "رملى",
            age: "15 سنوات",
            award: "160.000 ر.س",
          },
          {
            id: 14,
            name: "اسم السباق 14",
            classification: "التصنيف 14",
            date: "06/14/2024",
            day: "الجمعة",
            time: "06:30 PM - 04:30 PM",
            distance: "كم 17",
            type: "عشبى",
            age: "16 سنوات",
            award: "165.000 ر.س",
          },
          {
            id: 15,
            name: "اسم السباق 15",
            classification: "التصنيف 15",
            date: "06/15/2024",
            day: "السبت",
            time: "07:30 PM - 05:30 PM",
            distance: "كم 18",
            type: "رملى",
            age: "17 سنوات",
            award: "170.000 ر.س",
          },
          {
            id: 16,
            name: "اسم السباق 16",
            classification: "التصنيف 16",
            date: "06/16/2024",
            day: "الأحد",
            time: "08:30 PM - 06:30 PM",
            distance: "كم 19",
            type: "عشبى",
            age: "18 سنوات",
            award: "175.000 ر.س",
          },
          {
            id: 17,
            name: "اسم السباق 17",
            classification: "التصنيف 17",
            date: "06/17/2024",
            day: "الاثنين",
            time: "09:30 PM - 07:30 PM",
            distance: "كم 20",
            type: "رملى",
            age: "19 سنوات",
            award: "180.000 ر.س",
          },
          {
            id: 18,
            name: "اسم السباق 18",
            classification: "التصنيف 18",
            date: "06/18/2024",
            day: "الثلاثاء",
            time: "10:30 PM - 08:30 PM",
            distance: "كم 21",
            type: "عشبى",
            age: "20 سنوات",
            award: "185.000 ر.س",
          },
          {
            id: 19,
            name: "اسم السباق 19",
            classification: "التصنيف 19",
            date: "06/19/2024",
            day: "الأربعاء",
            time: "11:30 PM - 09:30 PM",
            distance: "كم 22",
            type: "رملى",
            age: "21 سنوات",
            award: "190.000 ر.س",
          },
          {
            id: 20,
            name: "اسم السباق 20",
            classification: "التصنيف 20",
            date: "06/20/2024",
            day: "الخميس",
            time: "12:30 PM - 10:30 AM",
            distance: "كم 23",
            type: "عشبى",
            age: "22 سنوات",
            award: "195.000 ر.س",
          },
          {
            id: 21,
            name: "اسم السباق 21",
            classification: "التصنيف 21",
            date: "06/21/2024",
            day: "الجمعة",
            time: "01:30 PM - 11:30 AM",
            distance: "كم 24",
            type: "رملى",
            age: "23 سنوات",
            award: "200.000 ر.س",
          },
          {
            id: 22,
            name: "اسم السباق 22",
            classification: "التصنيف 22",
            date: "06/22/2024",
            day: "السبت",
            time: "02:30 PM - 12:30 PM",
            distance: "كم 25",
            type: "عشبى",
            age: "24 سنوات",
            award: "205.000 ر.س",
          },
          {
            id: 23,
            name: "اسم السباق 23",
            classification: "التصنيف 23",
            date: "06/23/2024",
            day: "الأحد",
            time: "03:30 PM - 01:30 PM",
            distance: "كم 26",
            type: "رملى",
            age: "25 سنوات",
            award: "210.000 ر.س",
          },
          {
            id: 24,
            name: "اسم السباق 24",
            classification: "التصنيف 24",
            date: "06/24/2024",
            day: "الاثنين",
            time: "04:30 PM - 02:30 PM",
            distance: "كم 27",
            type: "عشبى",
            age: "26 سنوات",
            award: "215.000 ر.س",
          },
          {
            id: 25,
            name: "اسم السباق 25",
            classification: "التصنيف 25",
            date: "06/25/2024",
            day: "الثلاثاء",
            time: "05:30 PM - 03:30 PM",
            distance: "كم 28",
            type: "رملى",
            age: "27 سنوات",
            award: "220.000 ر.س",
          },
          {
            id: 26,
            name: "اسم السباق 26",
            classification: "التصنيف 26",
            date: "06/26/2024",
            day: "الأربعاء",
            time: "06:30 PM - 04:30 PM",
            distance: "كم 29",
            type: "عشبى",
            age: "28 سنوات",
            award: "225.000 ر.س",
          },
          {
            id: 27,
            name: "اسم السباق 27",
            classification: "التصنيف 27",
            date: "06/27/2024",
            day: "الخميس",
            time: "07:30 PM - 05:30 PM",
            distance: "كم 30",
            type: "رملى",
            age: "29 سنوات",
            award: "230.000 ر.س",
          },
          {
            id: 28,
            name: "اسم السباق 28",
            classification: "التصنيف 28",
            date: "06/28/2024",
            day: "الجمعة",
            time: "08:30 PM - 06:30 PM",
            distance: "كم 31",
            type: "عشبى",
            age: "30 سنوات",
            award: "235.000 ر.س",
          },
          {
            id: 29,
            name: "اسم السباق 29",
            classification: "التصنيف 29",
            date: "06/29/2024",
            day: "السبت",
            time: "09:30 PM - 07:30 PM",
            distance: "كم 32",
            type: "رملى",
            age: "31 سنوات",
            award: "240.000 ر.س",
          },
          {
            id: 30,
            name: "اسم السباق 30",
            classification: "التصنيف 30",
            date: "06/30/2024",
            day: "الأحد",
            time: "10:30 PM - 08:30 PM",
            distance: "كم 33",
            type: "عشبى",
            age: "32 سنوات",
            award: "245.000 ر.س",
          },
        ],
        "02": [
          {
            id: 1,
            name: "اسم السباق 1",
            classification: "التصنيف 1",
            date: "06/01/2024",
            day: "السبت",
            time: "05:30 PM - 03:30 PM",
            distance: "كم 4",
            type: "رملى",
            age: "3 سنوات",
            award: "100.000 ر.س",
          },
          {
            id: 2,
            name: "اسم السباق 2",
            classification: "التصنيف 2",
            date: "06/02/2024",
            day: "الأحد",
            time: "06:30 PM - 04:30 PM",
            distance: "كم 5",
            type: "عشبى",
            age: "4 سنوات",
            award: "105.000 ر.س",
          },
          {
            id: 3,
            name: "اسم السباق 3",
            classification: "التصنيف 3",
            date: "06/03/2024",
            day: "الاثنين",
            time: "07:30 PM - 05:30 PM",
            distance: "كم 6",
            type: "رملى",
            age: "5 سنوات",
            award: "110.000 ر.س",
          },
          {
            id: 4,
            name: "اسم السباق 4",
            classification: "التصنيف 4",
            date: "06/04/2024",
            day: "الثلاثاء",
            time: "08:30 PM - 06:30 PM",
            distance: "كم 7",
            type: "عشبى",
            age: "6 سنوات",
            award: "115.000 ر.س",
          },
          {
            id: 5,
            name: "اسم السباق 5",
            classification: "التصنيف 5",
            date: "06/05/2024",
            day: "الأربعاء",
            time: "09:30 PM - 07:30 PM",
            distance: "كم 8",
            type: "رملى",
            age: "7 سنوات",
            award: "120.000 ر.س",
          },
          {
            id: 6,
            name: "اسم السباق 6",
            classification: "التصنيف 6",
            date: "06/06/2024",
            day: "الخميس",
            time: "10:30 PM - 08:30 PM",
            distance: "كم 9",
            type: "عشبى",
            age: "8 سنوات",
            award: "125.000 ر.س",
          },
          {
            id: 7,
            name: "اسم السباق 7",
            classification: "التصنيف 7",
            date: "06/07/2024",
            day: "الجمعة",
            time: "11:30 PM - 09:30 PM",
            distance: "كم 10",
            type: "رملى",
            age: "9 سنوات",
            award: "130.000 ر.س",
          },
          {
            id: 8,
            name: "اسم السباق 8",
            classification: "التصنيف 8",
            date: "06/08/2024",
            day: "السبت",
            time: "12:30 PM - 10:30 AM",
            distance: "كم 11",
            type: "عشبى",
            age: "10 سنوات",
            award: "135.000 ر.س",
          },
          {
            id: 9,
            name: "اسم السباق 9",
            classification: "التصنيف 9",
            date: "06/09/2024",
            day: "الأحد",
            time: "01:30 PM - 11:30 AM",
            distance: "كم 12",
            type: "رملى",
            age: "11 سنوات",
            award: "140.000 ر.س",
          },
          {
            id: 10,
            name: "اسم السباق 10",
            classification: "التصنيف 10",
            date: "06/10/2024",
            day: "الاثنين",
            time: "02:30 PM - 12:30 PM",
            distance: "كم 13",
            type: "عشبى",
            age: "12 سنوات",
            award: "145.000 ر.س",
          },
        ],
        "03": [],
        "04": [],
        "05": [],
        "06": [],
      },
    },
  },
];
export const months = [
  "يناير",
  "فبراير",
  "مارس",
  "أبريل",
  "مايو",
  "يونيو",
  "يوليو",
  "أغسطس",
  "سبتمبر",
  "أكتوبر",
  "نوفمبر",
  "ديسمبر",
];
